-- 0.Init_DB.sql
USE [master];
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'OK2SHIP_SMT')
BEGIN
    CREATE DATABASE [OK2SHIP_SMT];
END
GO

-- Đảm bảo không có kết nối nào khác đang chiếm giữ DB khi Alter
ALTER DATABASE [OK2SHIP_SMT] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE [OK2SHIP_SMT] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [OK2SHIP_SMT] SET READ_COMMITTED_SNAPSHOT ON;
GO
ALTER DATABASE [OK2SHIP_SMT] SET MULTI_USER;
GO