// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"export_module_service/internal/delivery/amqp"
	"export_module_service/internal/infrastructure/repository"
	"export_module_service/internal/infrastructure/storage"
	"export_module_service/internal/usecase"
	"github.com/minio/minio-go/v7"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeWorker(minioClient *minio.Client, repo *gorm.DB) *amqp.Consumer {
	logStorage := storage.NewMinioStorage(minioClient)
	repository := repository.NewGormRepo(repo)
	peelTestUC := usecase.NewPeelTestUC(logStorage, repository)
	consumer := amqp.NewConsumer(peelTestUC)
	return consumer
}
